install.packages("ggplot2")
install.packages("gridExtra")
install.packages("plyr")
install.packages("stringr")
install.packages("forcats")
install.packages("scales")
install.packages("forcats")
install.packages("ExpDes")
install.packages("dplyr")
install.packages("ExpDes.pt")
install.packages("reshape2")
install.packages("data.table")
install.packages("kableExtra")

